apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbuddy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbuddy-backend
  template:
    metadata:
      labels:
        app: testbuddy-backend
    spec:
      containers:
      - name: testbuddy-backend
        image: testbuddy-backend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: testbuddy-service
spec:
  type: NodePort
  selector:
    app: testbuddy-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 
      nodePort: 30080
