apiVersion: v1
kind: Service
metadata:
  name: testbuddy-service
spec:
  type: NodePort
  selector:
    app: testbuddy-backend
  ports:
    - protocol: TCP
      port: 3000           # Port to access inside cluster
      targetPort: 3000     # Port the container is listening on
      nodePort: 30080      # Port on your localhost/minikube node
